// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBNmjl4M5aA6I-gcrMRd9dgM6CfRqgOYw',
    appId: '1:191097805539:android:f263d89e455641324f43d6',
    messagingSenderId: '191097805539',
    projectId: 'firstdiner-473d4f',
    storageBucket: 'firstdiner-473d4f.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAOOgLmIaytw3-HYxcKNUOVqy8nmABwAQ',
    appId: '1:191097805539:ios:8c9c0e9fc28446f74f43d6',
    messagingSenderId: '191097805539',
    projectId: 'firstdiner-473d4f',
    storageBucket: 'firstdiner-473d4f.firebasestorage.app',
    iosBundleId: 'com.firstdiner.firstdiner',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYmx7y5OZfgdkCsBzqttedmCZcbracGjg',
    appId: '1:191097805539:web:3f44662b745561d74f43d6',
    messagingSenderId: '191097805539',
    projectId: 'firstdiner-473d4f',
    authDomain: 'firstdiner-473d4f.firebaseapp.com',
    storageBucket: 'firstdiner-473d4f.firebasestorage.app',
  );
}
