import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:provider/provider.dart';
import 'config.dart';
import 'firebase_options.dart'; // generated by `flutterfire configure`
import 'state/app_state.dart';
import 'screens/splash.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  runApp(
    ChangeNotifierProvider(
      create: (_) => AppState(),
      child: const FirstDinerApp(),
    ),
  );
}

class FirstDinerApp extends StatelessWidget {
  const FirstDinerApp({super.key});
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'First Diner',
      debugShowCheckedModeBanner: false,
      theme: buildTheme(),
      home: const SplashScreen(),
    );
  }
}
